services:
  - type: web
    name: isamc-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: EMAIL_PROVIDER
        value: brevo
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Render will set this automatically, but you can override if needed
    autoDeploy: true 
